name: dart_open_toohit
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ">=3.0.0-134.0.dev <4.0.0"

# Add regular dependencies here.
dependencies:
  path: ^1.8.0
  meta: ^1.3.0
  freezed_annotation: ^2.2.0
  

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
  pedantic: ^1.9.0
  freezed: ^2.3.3
  build_runner: ^2.4.1
